# fly.toml app configuration file generated for vert-server on 2023-07-26T23:19:10+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "vert-server"
primary_region = "ams"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
